"""empty message

Revision ID: cbf554e24187
Revises: 4ac3c4e05668
Create Date: 2017-08-01 13:35:21.654982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf554e24187'
down_revision = '4ac3c4e05668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('network_id', sa.String(length=60), nullable=True))
    op.add_column('employees', sa.Column('network_type', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_employees_network_id'), 'employees', ['network_id'], unique=False)
    op.create_index(op.f('ix_employees_network_type'), 'employees', ['network_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_network_type'), table_name='employees')
    op.drop_index(op.f('ix_employees_network_id'), table_name='employees')
    op.drop_column('employees', 'network_type')
    op.drop_column('employees', 'network_id')
    # ### end Alembic commands ###
